=== EvanLoaf/java-practice/src/com/gmail/evanloafakahaitao/hwk/hwk20/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<shop:schema xmlns:shop="http://www.w3.org/2001/XMLSchema"
             xmlns="https://www.gmail.com/evanloafakahaitao"
             targetNamespace="https://www.gmail.com/evanloafakahaitao"
             elementFormDefault="qualified"
             attributeFormDefault="qualified">
    <shop:element name="catalogue" type="root"/>
    <shop:complexType name="root">
        <shop:sequence>
            <shop:element name="stock" type="stockType" minOccurs="0" maxOccurs="unbounded"/>
        </shop:sequence>
    </shop:complexType>
    <shop:complexType name="stockType">
        <shop:sequence>
            <shop:group ref="stockGroup"/>
            <shop:element name="category" type="categoryType"/>
            <shop:element name="stockDailyRecords" type="stockDailyRecordsType"/>
        </shop:sequence>
    </shop:complexType>
    <shop:group name="stockGroup">
        <shop:sequence>
            <shop:element name="stockId" type="stockIdType"/>
            <shop:element name="stockCode" type="stockCodeType"/>
            <shop:element name="stockName" type="stockNameType"/>
        </shop:sequence>
    </shop:group>
    <shop:simpleType name="stockIdType">
        <shop:restriction base="shop:integer">
            <shop:pattern value="[0-9]+"/>
        </shop:restriction>
    </shop:simpleType>
    <shop:simpleType name="stockCodeType">
        <shop:restriction base="shop:string">
            <shop:length value="10"/>
        </shop:restriction>
    </shop:simpleType>
    <shop:simpleType name="stockNameType">
        <shop:restriction base="shop:string">
            <shop:enumeration value="Tesla"/>
            <shop:enumeration value="AMC"/>
            <shop:enumeration value="GameStop"/>
        </shop:restriction>
    </shop:simpleType>
    <shop:complexType name="categoryType">
        <shop:sequence>
            <shop:element name="categoryId" type="categoryIdType"/>
            <shop:element name="categoryName" type="categoryNameType"/>
            <shop:element name="categoryDescription" type="categoryDescriptionType"/>
        </shop:sequence>
    </shop:complexType>
    <shop:simpleType name="categoryIdType">
        <shop:restriction base="shop:integer">
            <shop:pattern value="[0-9]{1,2}"/>
        </shop:restriction>
    </shop:simpleType>
    <shop:simpleType name="categoryNameType">
        <shop:restriction base="shop:string">
            <shop:enumeration value="entertainment"/>
            <shop:enumeration value="retail"/>
            <shop:enumeration value="manufacturing"/>
        </shop:restriction>
    </shop:simpleType>
    <shop:simpleType name="categoryDescriptionType">
        <shop:restriction base="shop:string">
            <shop:maxLength value="50"/>
        </shop:restriction>
    </shop:simpleType>
    <shop:complexType name="stockDailyRecordsType">
        <shop:sequence>
            <shop:element name="stockDailyRecord" maxOccurs="20" minOccurs="0">
                <shop:complexType>
                    <shop:sequence>
                        <shop:element name="recordId" type="shop:integer"/>
                        <shop:element name="recordPriceOpen" type="shop:float"/>
                        <shop:element name="recordPriceClose" type="shop:float"/>
                        <shop:element name="recordPriceChange" type="shop:float"/>
                        <shop:element name="recordVolume" type="shop:long"/>
                        <shop:element name="recordDate" type="shop:date"/>
                    </shop:sequence>
                </shop:complexType>
            </shop:element>
        </shop:sequence>
    </shop:complexType>
</shop:schema>

=== EvanLoaf/java-practice/src/com/gmail/evanloafakahaitao/hwk/hwk20/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogue xmlns="https://www.gmail.com/evanloafakahaitao"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://www.gmail.com/evanloafakahaitao schema.xsd">
    <stock>
        <stockId>120</stockId>
        <stockCode>15xx7dv2o3</stockCode>
        <stockName>Tesla</stockName>
        <category>
            <categoryId>55</categoryId>
            <categoryName>manufacturing</categoryName>
            <categoryDescription>Very long description for the supastock</categoryDescription>
        </category>
        <stockDailyRecords>
            <stockDailyRecord>
                <recordId>2</recordId>
                <recordPriceOpen>4.4</recordPriceOpen>
                <recordPriceClose>2.2</recordPriceClose>
                <recordPriceChange>6.6</recordPriceChange>
                <recordVolume>3</recordVolume>
                <recordDate>2020-10-21</recordDate>
            </stockDailyRecord>
            <stockDailyRecord>
                <recordId>1</recordId>
                <recordPriceOpen>3</recordPriceOpen>
                <recordPriceClose>4.3</recordPriceClose>
                <recordPriceChange>5.6</recordPriceChange>
                <recordVolume>6</recordVolume>
                <recordDate>2020-10-20</recordDate>
            </stockDailyRecord>
        </stockDailyRecords>
    </stock>
    <stock>
        <stockId>555</stockId>
        <stockCode>123456abcd</stockCode>
        <stockName>GameStop</stockName>
        <category>
            <categoryId>22</categoryId>
            <categoryName>retail</categoryName>
            <categoryDescription>Wow gamestop is cool</categoryDescription>
        </category>
        <stockDailyRecords>
            <stockDailyRecord>
                <recordId>1</recordId>
                <recordPriceOpen>2</recordPriceOpen>
                <recordPriceClose>3</recordPriceClose>
                <recordPriceChange>4</recordPriceChange>
                <recordVolume>10</recordVolume>
                <recordDate>2020-10-20</recordDate>
            </stockDailyRecord>
        </stockDailyRecords>
    </stock>
</catalogue>
